/* words.js — 本地词库（考研阅读高频词汇，离线可用，无需联网或 API）
 * 字段：w = 英文单词，c = 中文释义（用于「自动显示释义」与「英选译」选项）
 * 仅供本机查词与练习使用；生词本单独存于 localStorage。 */
window.DICTIONARY = [
  { w: 'abandon', c: 'v. 放弃；抛弃' },
  { w: 'abstract', c: 'adj. 抽象的；n. 摘要' },
  { w: 'academic', c: 'adj. 学术的；学院的' },
  { w: 'access', c: 'n./v. 接近；使用权限' },
  { w: 'accommodate', c: 'v. 容纳；适应；提供住宿' },
  { w: 'accompany', c: 'v. 陪伴；伴随' },
  { w: 'accumulate', c: 'v. 积累；积聚' },
  { w: 'accurate', c: 'adj. 准确的；精确的' },
  { w: 'achieve', c: 'v. 达到；实现' },
  { w: 'acquire', c: 'v. 获得；习得' },
  { w: 'adapt', c: 'v. 适应；改编' },
  { w: 'adequate', c: 'adj. 足够的；适当的' },
  { w: 'adjacent', c: 'adj. 邻近的；相邻的' },
  { w: 'adjust', c: 'v. 调整；适应' },
  { w: 'administer', c: 'v. 管理；执行' },
  { w: 'advocate', c: 'v. 提倡；n. 拥护者' },
  { w: 'affect', c: 'v. 影响；感动' },
  { w: 'aggregate', c: 'v./n. 合计；聚集' },
  { w: 'allocate', c: 'v. 分配；拨出' },
  { w: 'alter', c: 'v. 改变；修改' },
  { w: 'alternative', c: 'n. 替代物；adj. 可替代的' },
  { w: 'ambiguous', c: 'adj. 模棱两可的' },
  { w: 'ambitious', c: 'adj. 有雄心的；宏大的' },
  { w: 'analyse', c: 'v. 分析' },
  { w: 'ancient', c: 'adj. 古老的；古代的' },
  { w: 'announce', c: 'v. 宣布；通告' },
  { w: 'annual', c: 'adj. 每年的；年度的' },
  { w: 'anticipate', c: 'v. 预期；预料' },
  { w: 'apparent', c: 'adj. 明显的；表面的' },
  { w: 'appeal', c: 'v./n. 呼吁；吸引；上诉' },
  { w: 'approach', c: 'v. 接近；n. 方法；途径' },
  { w: 'appropriate', c: 'adj. 合适的；恰当的' },
  { w: 'approximate', c: 'adj. 近似的；大约的' },
  { w: 'arbitrary', c: 'adj. 任意的；武断的' },
  { w: 'argue', c: 'v. 争论；主张' },
  { w: 'arise', c: 'v. 出现；产生' },
  { w: 'aspect', c: 'n. 方面；面貌' },
  { w: 'assess', c: 'v. 评估；评定' },
  { w: 'assume', c: 'v. 假设；承担' },
  { w: 'attribute', c: 'v. 归因于；n. 特质' },
  { w: 'authority', c: 'n. 权威；当局' },
  { w: 'autonomous', c: 'adj. 自主的；自治的' },
  { w: 'available', c: 'adj. 可获得的；有空的' },
  { w: 'aware', c: 'adj. 意识到的；察觉的' },
  { w: 'benefit', c: 'n. 益处；v. 受益' },
  { w: 'bias', c: 'n. 偏见；偏向' },
  { w: 'boost', c: 'v./n. 提升；促进' },
  { w: 'brief', c: 'adj. 简短的；v. 简要介绍' },
  { w: 'broaden', c: 'v. 拓宽；使变宽' },
  { w: 'campaign', c: 'n. 运动；战役' },
  { w: 'capable', c: 'adj. 有能力的' },
  { w: 'cell', c: 'n. 细胞；单元格' },
  { w: 'challenge', c: 'n./v. 挑战' },
  { w: 'circumstance', c: 'n. 情况；环境' },
  { w: 'cite', c: 'v. 引用；引证' },
  { w: 'civil', c: 'adj. 公民的；民用的' },
  { w: 'clarify', c: 'v. 澄清；阐明' },
  { w: 'classic', c: 'adj. 经典的；n. 经典作品' },
  { w: 'cognitive', c: 'adj. 认知的' },
  { w: 'collapse', c: 'v./n. 倒塌；崩溃' },
  { w: 'commit', c: 'v. 承诺；犯（错）；投入' },
  { w: 'community', c: 'n. 社区；群体' },
  { w: 'compensate', c: 'v. 补偿；赔偿' },
  { w: 'compete', c: 'v. 竞争' },
  { w: 'complex', c: 'adj. 复杂的；n. 综合体' },
  { w: 'component', c: 'n. 成分；部件' },
  { w: 'comprehensive', c: 'adj. 全面的；综合的' },
  { w: 'comprise', c: 'v. 包含；由…组成' },
  { w: 'concept', c: 'n. 概念；观念' },
  { w: 'conclude', c: 'v. 得出结论；结束' },
  { w: 'consequence', c: 'n. 后果；结果' },
  { w: 'considerable', c: 'adj. 相当大的；可观的' },
  { w: 'consistent', c: 'adj. 一致的；始终如一的' },
  { w: 'constitute', c: 'v. 构成；组成' },
  { w: 'consume', c: 'v. 消耗；消费' },
  { w: 'contemporary', c: 'adj. 当代的；同时代的' },
  { w: 'context', c: 'n. 上下文；背景' },
  { w: 'contrary', c: 'adj. 相反的；n. 相反' },
  { w: 'contribute', c: 'v. 贡献；投稿' },
  { w: 'controversial', c: 'adj. 有争议的' },
  { w: 'conventional', c: 'adj. 传统的；常规的' },
  { w: 'convert', c: 'v. 转变；转换' },
  { w: 'cooperate', c: 'v. 合作' },
  { w: 'correspond', c: 'v. 符合；通信' },
  { w: 'create', c: 'v. 创造；创作' },
  { w: 'crucial', c: 'adj. 关键的；至关重要的' },
  { w: 'culture', c: 'n. 文化；培养' },
  { w: 'curious', c: 'adj. 好奇的' },
  { w: 'decline', c: 'v./n. 下降；拒绝' },
  { w: 'deduce', c: 'v. 推断；演绎' },
  { w: 'define', c: 'v. 定义；界定' },
  { w: 'deliberate', c: 'adj. 故意的；v. 仔细考虑' },
  { w: 'demonstrate', c: 'v. 证明；演示；示威' },
  { w: 'dense', c: 'adj. 密集的；稠密的' },
  { w: 'depend', c: 'v. 依赖；取决于' },
  { w: 'derive', c: 'v. 源于；获得' },
  { w: 'despite', c: 'prep. 尽管；不管' },
  { w: 'detect', c: 'v. 察觉；探测' },
  { w: 'deviate', c: 'v. 偏离；背离' },
  { w: 'distinct', c: 'adj. 明显的；独特的' },
  { w: 'distribute', c: 'v. 分配；分发' },
  { w: 'diverse', c: 'adj. 多样的；不同的' },
  { w: 'document', c: 'n. 文件；v. 记录' },
  { w: 'domain', c: 'n. 领域；域名' },
  { w: 'domestic', c: 'adj. 国内的；家庭的' },
  { w: 'dominant', c: 'adj. 主导的；占优势的' },
  { w: 'dramatic', c: 'adj. 戏剧性的；显著的' },
  { w: 'economy', c: 'n. 经济；节约' },
  { w: 'educational', c: 'adj. 教育的' },
  { w: 'elaborate', c: 'adj. 详尽的；v. 详细阐述' },
  { w: 'element', c: 'n. 元素；要素' },
  { w: 'emerge', c: 'v. 出现；浮现' },
  { w: 'emphasis', c: 'n. 强调；重点' },
  { w: 'enhance', c: 'v. 提高；增强' },
  { w: 'enormous', c: 'adj. 巨大的；庞大的' },
  { w: 'ensure', c: 'v. 确保；保证' },
  { w: 'environment', c: 'n. 环境' },
  { w: 'equate', c: 'v. 等同；使相等' },
  { w: 'establish', c: 'v. 建立；确立' },
  { w: 'estimate', c: 'v./n. 估计；估算' },
  { w: 'evaluate', c: 'v. 评价；评估' },
  { w: 'evident', c: 'adj. 明显的；明白的' },
  { w: 'evolve', c: 'v. 进化；逐步发展' },
  { w: 'exceed', c: 'v. 超过；超出' },
  { w: 'exclude', c: 'v. 排除；不包括' },
  { w: 'expand', c: 'v. 扩张；扩展' },
  { w: 'exploit', c: 'v. 利用；开发；剥削' },
  { w: 'export', c: 'v./n. 出口；输出' },
  { w: 'expose', c: 'v. 暴露；使接触' },
  { w: 'extract', c: 'v. 提取；摘录' },
  { w: 'factor', c: 'n. 因素；要素' },
  { w: 'feature', c: 'n. 特征；v. 以…为特色' },
  { w: 'federal', c: 'adj. 联邦的' },
  { w: 'financial', c: 'adj. 财政的；金融的' },
  { w: 'flexible', c: 'adj. 灵活的；柔韧的' },
  { w: 'focus', c: 'v./n. 集中；焦点' },
  { w: 'formula', c: 'n. 公式；配方' },
  { w: 'function', c: 'n. 功能；v. 运转' },
  { w: 'fundamental', c: 'adj. 基本的；根本的' },
  { w: 'generate', c: 'v. 产生；生成' },
  { w: 'global', c: 'adj. 全球的；总体的' },
  { w: 'gradient', c: 'n. 梯度；倾斜度' },
  { w: 'hypothesis', c: 'n. 假设；假说' },
  { w: 'identify', c: 'v. 识别；确认' },
  { w: 'illustrate', c: 'v. 说明；图解' },
  { w: 'immense', c: 'adj. 巨大的；广大的' },
  { w: 'implement', c: 'v. 实施；执行' },
  { w: 'implicate', c: 'v. 暗示；涉及' },
  { w: 'imply', c: 'v. 暗示；意味着' },
  { w: 'incentive', c: 'n. 激励；刺激' },
  { w: 'incorporate', c: 'v. 合并；包含' },
  { w: 'indicate', c: 'v. 表明；指示' },
  { w: 'individual', c: 'adj. 个人的；n. 个人' },
  { w: 'inevitable', c: 'adj. 不可避免的' },
  { w: 'influence', c: 'n./v. 影响' },
  { w: 'inhibit', c: 'v. 抑制；阻止' },
  { w: 'initial', c: 'adj. 最初的；n. 首字母' },
  { w: 'innovative', c: 'adj. 创新的' },
  { w: 'instance', c: 'n. 实例；情况' },
  { w: 'integral', c: 'adj. 完整的；不可或缺的' },
  { w: 'internal', c: 'adj. 内部的；国内的' },
  { w: 'interpret', c: 'v. 解释；口译' },
  { w: 'involve', c: 'v. 涉及；包含' },
  { w: 'isolate', c: 'v. 隔离；孤立' },
  { w: 'lack', c: 'v./n. 缺乏；不足' },
  { w: 'legitimate', c: 'adj. 合法的；合理的' },
  { w: 'likelihood', c: 'n. 可能性' },
  { w: 'maintain', c: 'v. 维持；保养' },
  { w: 'massive', c: 'adj. 巨大的；大量的' },
  { w: 'mechanism', c: 'n. 机制；机理' },
  { w: 'method', c: 'n. 方法' },
  { w: 'migrate', c: 'v. 迁移；移居' },
  { w: 'motive', c: 'n. 动机；原因' },
  { w: 'neutral', c: 'adj. 中立的；中性的' },
  { w: 'notion', c: 'n. 概念；想法' },
  { w: 'objective', c: 'n. 目标；adj. 客观的' },
  { w: 'obvious', c: 'adj. 明显的' },
  { w: 'obtain', c: 'v. 获得；得到' },
  { w: 'occur', c: 'v. 发生；出现' },
  { w: 'option', c: 'n. 选择；选项' },
  { w: 'origin', c: 'n. 起源；来源' },
  { w: 'overall', c: 'adj. 总体的；adv. 大体上' },
  { w: 'overlap', c: 'v./n. 重叠' },
  { w: 'parallel', c: 'adj. 平行的；n. 平行线' },
  { w: 'particular', c: 'adj. 特定的；特别的' },
  { w: 'phenomenon', c: 'n. 现象' },
  { w: 'physical', c: 'adj. 身体的；物理的' },
  { w: 'policy', c: 'n. 政策；方针' },
  { w: 'precise', c: 'adj. 精确的；准确的' },
  { w: 'predict', c: 'v. 预测' },
  { w: 'principal', c: 'adj. 主要的；n. 校长；本金' },
  { w: 'principle', c: 'n. 原则；原理' },
  { w: 'proceed', c: 'v. 继续；进行' },
  { w: 'process', c: 'n. 过程；v. 处理' },
  { w: 'prominent', c: 'adj. 突出的；显著的' },
  { w: 'promote', c: 'v. 促进；提升' },
  { w: 'proportion', c: 'n. 比例；部分' },
  { w: 'publish', c: 'v. 出版；发表' },
  { w: 'purpose', c: 'n. 目的；意图' },
  { w: 'pursue', c: 'v. 追求；从事' },
  { w: 'qualitative', c: 'adj. 定性的' },
  { w: 'radical', c: 'adj. 根本的；激进的' },
  { w: 'random', c: 'adj. 随机的' },
  { w: 'range', c: 'n. 范围；v. 变化' },
  { w: 'react', c: 'v. 反应；回应' },
  { w: 'region', c: 'n. 地区；区域' },
  { w: 'regulate', c: 'v. 调节；管制' },
  { w: 'relate', c: 'v. 关联；叙述' },
  { w: 'relevant', c: 'adj. 相关的' },
  { w: 'rely', c: 'v. 依靠；依赖' },
  { w: 'remain', c: 'v. 保持；剩余' },
  { w: 'replace', c: 'v. 取代；替换' },
  { w: 'require', c: 'v. 需要；要求' },
  { w: 'research', c: 'n./v. 研究' },
  { w: 'reside', c: 'v. 居住；位于' },
  { w: 'resource', c: 'n. 资源' },
  { w: 'respond', c: 'v. 回应；反应' },
  { w: 'restore', c: 'v. 恢复；修复' },
  { w: 'reveal', c: 'v. 揭示；展现' },
  { w: 'robust', c: 'adj. 强健的；稳健的' },
  { w: 'role', c: 'n. 角色；作用' },
  { w: 'section', c: 'n. 部分；章节' },
  { w: 'sector', c: 'n. 部门；行业' },
  { w: 'significant', c: 'adj. 重要的；显著的' },
  { w: 'similar', c: 'adj. 相似的' },
  { w: 'situation', c: 'n. 情况；形势' },
  { w: 'society', c: 'n. 社会' },
  { w: 'specific', c: 'adj. 具体的；特定的' },
  { w: 'specify', c: 'v. 具体说明' },
  { w: 'stable', c: 'adj. 稳定的' },
  { w: 'statistic', c: 'n. 统计；数据' },
  { w: 'status', c: 'n. 地位；状态' },
  { w: 'stress', c: 'n. 压力；v. 强调' },
  { w: 'structure', c: 'n. 结构；v. 组织' },
  { w: 'submit', c: 'v. 提交；屈服' },
  { w: 'subsequent', c: 'adj. 随后的；后来的' },
  { w: 'sufficient', c: 'adj. 足够的' },
  { w: 'suggest', c: 'v. 建议；暗示' },
  { w: 'summary', c: 'n. 摘要；总结' },
  { w: 'support', c: 'v./n. 支持' },
  { w: 'theory', c: 'n. 理论' },
  { w: 'therefore', c: 'adv. 因此；所以' },
  { w: 'threaten', c: 'v. 威胁；危及' },
  { w: 'tradition', c: 'n. 传统' },
  { w: 'transfer', c: 'v./n. 转移；转让' },
  { w: 'transform', c: 'v. 转变；改造' },
  { w: 'transmit', c: 'v. 传播；传输' },
  { w: 'ultimately', c: 'adv. 最终；根本地' },
  { w: 'unique', c: 'adj. 独特的；唯一的' },
  { w: 'valid', c: 'adj. 有效的；合理的' },
  { w: 'vary', c: 'v. 变化；不同' },
  { w: 'vehicle', c: 'n. 车辆；媒介' },
  { w: 'version', c: 'n. 版本；说法' },
  { w: 'welfare', c: 'n. 福利；福祉' },
  { w: 'whereas', c: 'conj. 然而；鉴于' },
  { w: 'widespread', c: 'adj. 广泛的；普遍的' }
];
