  1→/* words.js — 本地词库（考研阅读高频词汇，离线可用，无需联网或 API）
  2→ * 字段：w = 英文单词，c = 中文释义（用于「自动显示释义」与「英选译」选项）
  3→ * 仅供本机查词与练习使用；生词本单独存于 localStorage。 */
  4→window.DICTIONARY = [
  5→  { w: 'abandon', c: 'v. 放弃；抛弃' },
  6→  { w: 'abstract', c: 'adj. 抽象的；n. 摘要' },
  7→  { w: 'academic', c: 'adj. 学术的；学院的' },
  8→  { w: 'access', c: 'n./v. 接近；使用权限' },
  9→  { w: 'accommodate', c: 'v. 容纳；适应；提供住宿' },
 10→  { w: 'accompany', c: 'v. 陪伴；伴随' },
 11→  { w: 'accumulate', c: 'v. 积累；积聚' },
 12→  { w: 'accurate', c: 'adj. 准确的；精确的' },
 13→  { w: 'achieve', c: 'v. 达到；实现' },
 14→  { w: 'acquire', c: 'v. 获得；习得' },
 15→  { w: 'adapt', c: 'v. 适应；改编' },
 16→  { w: 'adequate', c: 'adj. 足够的；适当的' },
 17→  { w: 'adjacent', c: 'adj. 邻近的；相邻的' },
 18→  { w: 'adjust', c: 'v. 调整；适应' },
 19→  { w: 'administer', c: 'v. 管理；执行' },
 20→  { w: 'advocate', c: 'v. 提倡；n. 拥护者' },
 21→  { w: 'affect', c: 'v. 影响；感动' },
 22→  { w: 'aggregate', c: 'v./n. 合计；聚集' },
 23→  { w: 'allocate', c: 'v. 分配；拨出' },
 24→  { w: 'alter', c: 'v. 改变；修改' },
 25→  { w: 'alternative', c: 'n. 替代物；adj. 可替代的' },
 26→  { w: 'ambiguous', c: 'adj. 模棱两可的' },
 27→  { w: 'ambitious', c: 'adj. 有雄心的；宏大的' },
 28→  { w: 'analyse', c: 'v. 分析' },
 29→  { w: 'ancient', c: 'adj. 古老的；古代的' },
 30→  { w: 'announce', c: 'v. 宣布；通告' },
 31→  { w: 'annual', c: 'adj. 每年的；年度的' },
 32→  { w: 'anticipate', c: 'v. 预期；预料' },
 33→  { w: 'apparent', c: 'adj. 明显的；表面的' },
 34→  { w: 'appeal', c: 'v./n. 呼吁；吸引；上诉' },
 35→  { w: 'approach', c: 'v. 接近；n. 方法；途径' },
 36→  { w: 'appropriate', c: 'adj. 合适的；恰当的' },
 37→  { w: 'approximate', c: 'adj. 近似的；大约的' },
 38→  { w: 'arbitrary', c: 'adj. 任意的；武断的' },
 39→  { w: 'argue', c: 'v. 争论；主张' },
 40→  { w: 'arise', c: 'v. 出现；产生' },
 41→  { w: 'aspect', c: 'n. 方面；面貌' },
 42→  { w: 'assess', c: 'v. 评估；评定' },
 43→  { w: 'assume', c: 'v. 假设；承担' },
 44→  { w: 'attribute', c: 'v. 归因于；n. 特质' },
 45→  { w: 'authority', c: 'n. 权威；当局' },
 46→  { w: 'autonomous', c: 'adj. 自主的；自治的' },
 47→  { w: 'available', c: 'adj. 可获得的；有空的' },
 48→  { w: 'aware', c: 'adj. 意识到的；察觉的' },
 49→  { w: 'benefit', c: 'n. 益处；v. 受益' },
 50→  { w: 'bias', c: 'n. 偏见；偏向' },
 51→  { w: 'boost', c: 'v./n. 提升；促进' },
 52→  { w: 'brief', c: 'adj. 简短的；v. 简要介绍' },
 53→  { w: 'broaden', c: 'v. 拓宽；使变宽' },
 54→  { w: 'campaign', c: 'n. 运动；战役' },
 55→  { w: 'capable', c: 'adj. 有能力的' },
 56→  { w: 'cell', c: 'n. 细胞；单元格' },
 57→  { w: 'challenge', c: 'n./v. 挑战' },
 58→  { w: 'circumstance', c: 'n. 情况；环境' },
 59→  { w: 'cite', c: 'v. 引用；引证' },
 60→  { w: 'civil', c: 'adj. 公民的；民用的' },
 61→  { w: 'clarify', c: 'v. 澄清；阐明' },
 62→  { w: 'classic', c: 'adj. 经典的；n. 经典作品' },
 63→  { w: 'cognitive', c: 'adj. 认知的' },
 64→  { w: 'collapse', c: 'v./n. 倒塌；崩溃' },
 65→  { w: 'commit', c: 'v. 承诺；犯（错）；投入' },
 66→  { w: 'community', c: 'n. 社区；群体' },
 67→  { w: 'compensate', c: 'v. 补偿；赔偿' },
 68→  { w: 'compete', c: 'v. 竞争' },
 69→  { w: 'complex', c: 'adj. 复杂的；n. 综合体' },
 70→  { w: 'component', c: 'n. 成分；部件' },
 71→  { w: 'comprehensive', c: 'adj. 全面的；综合的' },
 72→  { w: 'comprise', c: 'v. 包含；由…组成' },
 73→  { w: 'concept', c: 'n. 概念；观念' },
 74→  { w: 'conclude', c: 'v. 得出结论；结束' },
 75→  { w: 'consequence', c: 'n. 后果；结果' },
 76→  { w: 'considerable', c: 'adj. 相当大的；可观的' },
 77→  { w: 'consistent', c: 'adj. 一致的；始终如一的' },
 78→  { w: 'constitute', c: 'v. 构成；组成' },
 79→  { w: 'consume', c: 'v. 消耗；消费' },
 80→  { w: 'contemporary', c: 'adj. 当代的；同时代的' },
 81→  { w: 'context', c: 'n. 上下文；背景' },
 82→  { w: 'contrary', c: 'adj. 相反的；n. 相反' },
 83→  { w: 'contribute', c: 'v. 贡献；投稿' },
 84→  { w: 'controversial', c: 'adj. 有争议的' },
 85→  { w: 'conventional', c: 'adj. 传统的；常规的' },
 86→  { w: 'convert', c: 'v. 转变；转换' },
 87→  { w: 'cooperate', c: 'v. 合作' },
 88→  { w: 'correspond', c: 'v. 符合；通信' },
 89→  { w: 'create', c: 'v. 创造；创作' },
 90→  { w: 'crucial', c: 'adj. 关键的；至关重要的' },
 91→  { w: 'culture', c: 'n. 文化；培养' },
 92→  { w: 'curious', c: 'adj. 好奇的' },
 93→  { w: 'decline', c: 'v./n. 下降；拒绝' },
 94→  { w: 'deduce', c: 'v. 推断；演绎' },
 95→  { w: 'define', c: 'v. 定义；界定' },
 96→  { w: 'deliberate', c: 'adj. 故意的；v. 仔细考虑' },
 97→  { w: 'demonstrate', c: 'v. 证明；演示；示威' },
 98→  { w: 'dense', c: 'adj. 密集的；稠密的' },
 99→  { w: 'depend', c: 'v. 依赖；取决于' },
100→  { w: 'derive', c: 'v. 源于；获得' },
101→  { w: 'despite', c: 'prep. 尽管；不管' },
102→  { w: 'detect', c: 'v. 察觉；探测' },
103→  { w: 'deviate', c: 'v. 偏离；背离' },
104→  { w: 'distinct', c: 'adj. 明显的；独特的' },
105→  { w: 'distribute', c: 'v. 分配；分发' },
106→  { w: 'diverse', c: 'adj. 多样的；不同的' },
107→  { w: 'document', c: 'n. 文件；v. 记录' },
108→  { w: 'domain', c: 'n. 领域；域名' },
109→  { w: 'domestic', c: 'adj. 国内的；家庭的' },
110→  { w: 'dominant', c: 'adj. 主导的；占优势的' },
111→  { w: 'dramatic', c: 'adj. 戏剧性的；显著的' },
112→  { w: 'economy', c: 'n. 经济；节约' },
113→  { w: 'educational', c: 'adj. 教育的' },
114→  { w: 'elaborate', c: 'adj. 详尽的；v. 详细阐述' },
115→  { w: 'element', c: 'n. 元素；要素' },
116→  { w: 'emerge', c: 'v. 出现；浮现' },
117→  { w: 'emphasis', c: 'n. 强调；重点' },
118→  { w: 'enhance', c: 'v. 提高；增强' },
119→  { w: 'enormous', c: 'adj. 巨大的；庞大的' },
120→  { w: 'ensure', c: 'v. 确保；保证' },
121→  { w: 'environment', c: 'n. 环境' },
122→  { w: 'equate', c: 'v. 等同；使相等' },
123→  { w: 'establish', c: 'v. 建立；确立' },
124→  { w: 'estimate', c: 'v./n. 估计；估算' },
125→  { w: 'evaluate', c: 'v. 评价；评估' },
126→  { w: 'evident', c: 'adj. 明显的；明白的' },
127→  { w: 'evolve', c: 'v. 进化；逐步发展' },
128→  { w: 'exceed', c: 'v. 超过；超出' },
129→  { w: 'exclude', c: 'v. 排除；不包括' },
130→  { w: 'expand', c: 'v. 扩张；扩展' },
131→  { w: 'exploit', c: 'v. 利用；开发；剥削' },
132→  { w: 'export', c: 'v./n. 出口；输出' },
133→  { w: 'expose', c: 'v. 暴露；使接触' },
134→  { w: 'extract', c: 'v. 提取；摘录' },
135→  { w: 'factor', c: 'n. 因素；要素' },
136→  { w: 'feature', c: 'n. 特征；v. 以…为特色' },
137→  { w: 'federal', c: 'adj. 联邦的' },
138→  { w: 'financial', c: 'adj. 财政的；金融的' },
139→  { w: 'flexible', c: 'adj. 灵活的；柔韧的' },
140→  { w: 'focus', c: 'v./n. 集中；焦点' },
141→  { w: 'formula', c: 'n. 公式；配方' },
142→  { w: 'function', c: 'n. 功能；v. 运转' },
143→  { w: 'fundamental', c: 'adj. 基本的；根本的' },
144→  { w: 'generate', c: 'v. 产生；生成' },
145→  { w: 'global', c: 'adj. 全球的；总体的' },
146→  { w: 'gradient', c: 'n. 梯度；倾斜度' },
147→  { w: 'hypothesis', c: 'n. 假设；假说' },
148→  { w: 'identify', c: 'v. 识别；确认' },
149→  { w: 'illustrate', c: 'v. 说明；图解' },
150→  { w: 'immense', c: 'adj. 巨大的；广大的' },
151→  { w: 'implement', c: 'v. 实施；执行' },
152→  { w: 'implicate', c: 'v. 暗示；涉及' },
153→  { w: 'imply', c: 'v. 暗示；意味着' },
154→  { w: 'incentive', c: 'n. 激励；刺激' },
155→  { w: 'incorporate', c: 'v. 合并；包含' },
156→  { w: 'indicate', c: 'v. 表明；指示' },
157→  { w: 'individual', c: 'adj. 个人的；n. 个人' },
158→  { w: 'inevitable', c: 'adj. 不可避免的' },
159→  { w: 'influence', c: 'n./v. 影响' },
160→  { w: 'inhibit', c: 'v. 抑制；阻止' },
161→  { w: 'initial', c: 'adj. 最初的；n. 首字母' },
162→  { w: 'innovative', c: 'adj. 创新的' },
163→  { w: 'instance', c: 'n. 实例；情况' },
164→  { w: 'integral', c: 'adj. 完整的；不可或缺的' },
165→  { w: 'internal', c: 'adj. 内部的；国内的' },
166→  { w: 'interpret', c: 'v. 解释；口译' },
167→  { w: 'involve', c: 'v. 涉及；包含' },
168→  { w: 'isolate', c: 'v. 隔离；孤立' },
169→  { w: 'lack', c: 'v./n. 缺乏；不足' },
170→  { w: 'legitimate', c: 'adj. 合法的；合理的' },
171→  { w: 'likelihood', c: 'n. 可能性' },
172→  { w: 'maintain', c: 'v. 维持；保养' },
173→  { w: 'massive', c: 'adj. 巨大的；大量的' },
174→  { w: 'mechanism', c: 'n. 机制；机理' },
175→  { w: 'method', c: 'n. 方法' },
176→  { w: 'migrate', c: 'v. 迁移；移居' },
177→  { w: 'motive', c: 'n. 动机；原因' },
178→  { w: 'neutral', c: 'adj. 中立的；中性的' },
179→  { w: 'notion', c: 'n. 概念；想法' },
180→  { w: 'objective', c: 'n. 目标；adj. 客观的' },
181→  { w: 'obvious', c: 'adj. 明显的' },
182→  { w: 'obtain', c: 'v. 获得；得到' },
183→  { w: 'occur', c: 'v. 发生；出现' },
184→  { w: 'option', c: 'n. 选择；选项' },
185→  { w: 'origin', c: 'n. 起源；来源' },
186→  { w: 'overall', c: 'adj. 总体的；adv. 大体上' },
187→  { w: 'overlap', c: 'v./n. 重叠' },
188→  { w: 'parallel', c: 'adj. 平行的；n. 平行线' },
189→  { w: 'particular', c: 'adj. 特定的；特别的' },
190→  { w: 'phenomenon', c: 'n. 现象' },
191→  { w: 'physical', c: 'adj. 身体的；物理的' },
192→  { w: 'policy', c: 'n. 政策；方针' },
193→  { w: 'precise', c: 'adj. 精确的；准确的' },
194→  { w: 'predict', c: 'v. 预测' },
195→  { w: 'principal', c: 'adj. 主要的；n. 校长；本金' },
196→  { w: 'principle', c: 'n. 原则；原理' },
197→  { w: 'proceed', c: 'v. 继续；进行' },
198→  { w: 'process', c: 'n. 过程；v. 处理' },
199→  { w: 'prominent', c: 'adj. 突出的；显著的' },
200→  { w: 'promote', c: 'v. 促进；提升' },
201→  { w: 'proportion', c: 'n. 比例；部分' },
202→  { w: 'publish', c: 'v. 出版；发表' },
203→  { w: 'purpose', c: 'n. 目的；意图' },
204→  { w: 'pursue', c: 'v. 追求；从事' },
205→  { w: 'qualitative', c: 'adj. 定性的' },
206→  { w: 'radical', c: 'adj. 根本的；激进的' },
207→  { w: 'random', c: 'adj. 随机的' },
208→  { w: 'range', c: 'n. 范围；v. 变化' },
209→  { w: 'react', c: 'v. 反应；回应' },
210→  { w: 'region', c: 'n. 地区；区域' },
211→  { w: 'regulate', c: 'v. 调节；管制' },
212→  { w: 'relate', c: 'v. 关联；叙述' },
213→  { w: 'relevant', c: 'adj. 相关的' },
214→  { w: 'rely', c: 'v. 依靠；依赖' },
215→  { w: 'remain', c: 'v. 保持；剩余' },
216→  { w: 'replace', c: 'v. 取代；替换' },
217→  { w: 'require', c: 'v. 需要；要求' },
218→  { w: 'research', c: 'n./v. 研究' },
219→  { w: 'reside', c: 'v. 居住；位于' },
220→  { w: 'resource', c: 'n. 资源' },
221→  { w: 'respond', c: 'v. 回应；反应' },
222→  { w: 'restore', c: 'v. 恢复；修复' },
223→  { w: 'reveal', c: 'v. 揭示；展现' },
224→  { w: 'robust', c: 'adj. 强健的；稳健的' },
225→  { w: 'role', c: 'n. 角色；作用' },
226→  { w: 'section', c: 'n. 部分；章节' },
227→  { w: 'sector', c: 'n. 部门；行业' },
228→  { w: 'significant', c: 'adj. 重要的；显著的' },
229→  { w: 'similar', c: 'adj. 相似的' },
230→  { w: 'situation', c: 'n. 情况；形势' },
231→  { w: 'society', c: 'n. 社会' },
232→  { w: 'specific', c: 'adj. 具体的；特定的' },
233→  { w: 'specify', c: 'v. 具体说明' },
234→  { w: 'stable', c: 'adj. 稳定的' },
235→  { w: 'statistic', c: 'n. 统计；数据' },
236→  { w: 'status', c: 'n. 地位；状态' },
237→  { w: 'stress', c: 'n. 压力；v. 强调' },
238→  { w: 'structure', c: 'n. 结构；v. 组织' },
239→  { w: 'submit', c: 'v. 提交；屈服' },
240→  { w: 'subsequent', c: 'adj. 随后的；后来的' },
241→  { w: 'sufficient', c: 'adj. 足够的' },
242→  { w: 'suggest', c: 'v. 建议；暗示' },
243→  { w: 'summary', c: 'n. 摘要；总结' },
244→  { w: 'support', c: 'v./n. 支持' },
245→  { w: 'theory', c: 'n. 理论' },
246→  { w: 'therefore', c: 'adv. 因此；所以' },
247→  { w: 'threaten', c: 'v. 威胁；危及' },
248→  { w: 'tradition', c: 'n. 传统' },
249→  { w: 'transfer', c: 'v./n. 转移；转让' },
250→  { w: 'transform', c: 'v. 转变；改造' },
251→  { w: 'transmit', c: 'v. 传播；传输' },
252→  { w: 'ultimately', c: 'adv. 最终；根本地' },
253→  { w: 'unique', c: 'adj. 独特的；唯一的' },
254→  { w: 'valid', c: 'adj. 有效的；合理的' },
255→  { w: 'vary', c: 'v. 变化；不同' },
256→  { w: 'vehicle', c: 'n. 车辆；媒介' },
257→  { w: 'version', c: 'n. 版本；说法' },
258→  { w: 'welfare', c: 'n. 福利；福祉' },
259→  { w: 'whereas', c: 'conj. 然而；鉴于' },
260→  { w: 'widespread', c: 'adj. 广泛的；普遍的' }
261→];